name: Dockerized Angular CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Cache Node.js modules
    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Install dependencies and run tests
    - name: Install dependencies
      run: npm install

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t angular-frontend .

    # Test the Docker container
    - name: Test Docker container
      run: docker run -d -p 8080:80 angular-frontend

    # (Optional) Lint the code
    - name: Lint code
      run: npm run lint
